import { describe, expect, it } from 'vitest';
import { nationalHolidayDates } from '../holidays';
import {
  generateOccurrences,
  resolveDayRule,
  splitParts,
  splitRecurrenceFrom,
  type RecurrenceRule,
} from './index';

const holidays = nationalHolidayDates(2025, 2028);
const window = (from: string, to: string) => ({ from, to, holidays });

const salary: RecurrenceRule = {
  frequency: 'monthly',
  startDate: '2026-09-01',
  amount: 500000,
  parts: [
    {
      label: 'Adiantamento',
      percent: 40,
      dayRule: { kind: 'fixed_day', day: 15 },
      adjust: 'previous',
      monthOffset: 0,
    },
    { label: 'Salário', percent: 60, dayRule: { kind: 'nth_business_day', n: 5 }, monthOffset: 1 },
  ],
};

describe('resolveDayRule (RN 3)', () => {
  it('resolves each kind', () => {
    expect(resolveDayRule(2026, 4, { kind: 'fixed_day', day: 31 }, 'none', holidays)).toBe(
      '2026-04-30',
    );
    // 15/11/2026 é domingo e feriado → previous = sexta 13/11
    expect(resolveDayRule(2026, 11, { kind: 'fixed_day', day: 15 }, 'previous', holidays)).toBe(
      '2026-11-13',
    );
    expect(resolveDayRule(2026, 11, { kind: 'fixed_day', day: 15 }, 'next', holidays)).toBe(
      '2026-11-16',
    );
    expect(resolveDayRule(2026, 9, { kind: 'nth_business_day', n: 5 }, 'none', holidays)).toBe(
      '2026-09-08',
    );
    expect(resolveDayRule(2026, 10, { kind: 'last_business_day' }, 'none', holidays)).toBe(
      '2026-10-30',
    );
  });
});

describe('splitParts (RN 3)', () => {
  it('splits by percent with the remainder on the last part', () => {
    expect(splitParts(500000, salary.parts ?? [])).toEqual([200000, 300000]);
    const thirds = [33.33, 33.33, 33.34].map((percent) => ({
      percent,
      dayRule: { kind: 'last_business_day' as const },
    }));
    expect(splitParts(100001, thirds)).toEqual([33330, 33330, 33341]);
  });

  it('accepts fixed amounts that sum to the total', () => {
    const parts = [
      { amount: 150000, dayRule: { kind: 'fixed_day' as const, day: 15 } },
      { amount: 350000, dayRule: { kind: 'fixed_day' as const, day: 30 } },
    ];
    expect(splitParts(500000, parts)).toEqual([150000, 350000]);
    expect(() => splitParts(400000, parts)).toThrow(RangeError);
  });

  it('computes percent parts exactly for large totals', () => {
    const total = Number.MAX_SAFE_INTEGER;
    const dayRule = { kind: 'fixed_day' as const, day: 5 };
    const parts = [
      { percent: 66.67, dayRule },
      { amount: total - 6005099743135818, dayRule },
    ];
    expect(splitParts(total, parts)).toEqual([6005099743135818, 3002099511605173]);
    expect(
      splitParts(-10001, [
        { percent: 50, dayRule },
        { amount: -5000, dayRule },
      ]),
    ).toEqual([-5001, -5000]);
  });

  it('rejects invalid parts', () => {
    const dayRule = { kind: 'last_business_day' as const };
    expect(() => splitParts(100, [{ dayRule }])).toThrow(RangeError);
    expect(() => splitParts(100, [{ dayRule, amount: 100, percent: 100 }])).toThrow(RangeError);
    expect(() =>
      splitParts(100, [
        { dayRule, percent: 40 },
        { dayRule, percent: 50 },
      ]),
    ).toThrow(RangeError);
    expect(() => splitParts(100, [])).toThrow(RangeError);
  });
});

describe('generateOccurrences: salário dividido (RN 3)', () => {
  it('referência setembro/2026: R$ 2.000 em 15/09 e R$ 3.000 em 07/10', () => {
    const occ = generateOccurrences(salary, window('2026-09-01', '2026-10-31'));
    expect(occ).toEqual([
      { date: '2026-09-15', amount: 200000, reference: '2026-09', part: 0, label: 'Adiantamento' },
      { date: '2026-10-07', amount: 300000, reference: '2026-09', part: 1, label: 'Salário' },
      { date: '2026-10-15', amount: 200000, reference: '2026-10', part: 0, label: 'Adiantamento' },
    ]);
  });

  it('generates 12 months with the advance adjusted to the previous business day', () => {
    const occ = generateOccurrences(salary, window('2026-09-01', '2027-08-31'));
    // 12 adiantamentos + 11 salários (o de agosto/2027 cai em setembro, fora da janela)
    expect(occ).toHaveLength(23);
    expect(occ.reduce((a, o) => a + o.amount, 0)).toBe(12 * 200000 + 11 * 300000);
    // 15/11/2026 domingo/feriado → 13/11
    expect(occ.find((o) => o.reference === '2026-11' && o.part === 0)?.date).toBe('2026-11-13');
  });

  it('end date bounds the reference month, so the last salary still comes', () => {
    const occ = generateOccurrences(
      { ...salary, endDate: '2026-10-31' },
      window('2026-09-01', '2027-12-31'),
    );
    expect(occ.map((o) => o.date)).toEqual([
      '2026-09-15',
      '2026-10-07',
      '2026-10-15',
      '2026-11-09', // 5º dia útil de novembro/2026 (02 é feriado)
    ]);
  });

  it('respects the window even for parts generated by earlier months', () => {
    const occ = generateOccurrences(salary, window('2026-10-01', '2026-10-10'));
    expect(occ).toEqual([
      { date: '2026-10-07', amount: 300000, reference: '2026-09', part: 1, label: 'Salário' },
    ]);
  });
});

describe('generateOccurrences: frequências (RN 3)', () => {
  it('monthly fixed day with clamp and end date', () => {
    const rule: RecurrenceRule = {
      frequency: 'monthly',
      startDate: '2026-01-31',
      endDate: '2026-05-15',
      amount: 9990,
      dayRule: { kind: 'fixed_day', day: 31 },
    };
    expect(
      generateOccurrences(rule, window('2026-01-01', '2026-12-31')).map((o) => o.date),
    ).toEqual(['2026-01-31', '2026-02-28', '2026-03-31', '2026-04-30']);
  });

  it('skips dates before the start date', () => {
    const rule: RecurrenceRule = {
      frequency: 'monthly',
      startDate: '2026-09-20',
      amount: 1000,
      dayRule: { kind: 'fixed_day', day: 10 },
    };
    expect(
      generateOccurrences(rule, window('2026-09-01', '2026-11-30')).map((o) => o.date),
    ).toEqual(['2026-10-10', '2026-11-10']);
  });

  it('every n months', () => {
    const rule: RecurrenceRule = {
      frequency: 'every_n_months',
      interval: 3,
      startDate: '2026-01-10',
      amount: 1000,
      dayRule: { kind: 'fixed_day', day: 10 },
    };
    expect(
      generateOccurrences(rule, window('2026-05-01', '2027-01-31')).map((o) => o.date),
    ).toEqual(['2026-07-10', '2026-10-10', '2027-01-10']);
  });

  it('yearly', () => {
    const rule: RecurrenceRule = {
      frequency: 'yearly',
      startDate: '2024-02-29',
      amount: 50000,
      dayRule: { kind: 'fixed_day', day: 29 },
    };
    expect(
      generateOccurrences(rule, window('2025-01-01', '2028-12-31')).map((o) => o.date),
    ).toEqual(['2025-02-28', '2026-02-28', '2027-02-28', '2028-02-29']);
  });

  it('weekly, starting far before the window', () => {
    const rule: RecurrenceRule = {
      frequency: 'weekly',
      startDate: '2026-01-05',
      amount: 2500,
    };
    const occ = generateOccurrences(rule, window('2026-09-01', '2026-09-30'));
    expect(occ.map((o) => o.date)).toEqual([
      '2026-09-07',
      '2026-09-14',
      '2026-09-21',
      '2026-09-28',
    ]);
  });

  it('weekly every 2 weeks ignores adjust (only fixed_day adjusts)', () => {
    const rule: RecurrenceRule = {
      frequency: 'weekly',
      interval: 2,
      startDate: '2026-08-24',
      adjust: 'next',
      amount: 2500,
    };
    expect(
      generateOccurrences(rule, window('2026-08-01', '2026-09-30')).map((o) => o.date),
    ).toEqual(['2026-08-24', '2026-09-07', '2026-09-21']);
  });

  it('last business day', () => {
    const rule: RecurrenceRule = {
      frequency: 'monthly',
      startDate: '2026-10-01',
      amount: 100,
      dayRule: { kind: 'last_business_day' },
    };
    expect(
      generateOccurrences(rule, window('2026-10-01', '2027-01-31')).map((o) => o.date),
    ).toEqual(['2026-10-30', '2026-11-30', '2026-12-31', '2027-01-29']);
  });

  it('returns nothing for an inverted window and validates input', () => {
    const rule: RecurrenceRule = { frequency: 'monthly', startDate: '2026-01-01', amount: 100 };
    expect(generateOccurrences(rule, window('2026-02-01', '2026-01-01'))).toEqual([]);
    expect(() => generateOccurrences(rule, window('2026-01-01', '2026-12-31'))).toThrow(RangeError);
    expect(() =>
      generateOccurrences(
        { ...rule, amount: 1.5, dayRule: { kind: 'fixed_day', day: 1 } },
        window('2026-01-01', '2026-12-31'),
      ),
    ).toThrow(RangeError);
  });
});

describe('splitRecurrenceFrom (RN 3 Edição)', () => {
  it('ends the old rule in the previous month and starts the new one', () => {
    const { previous, next } = splitRecurrenceFrom(salary, '2027-01', { amount: 550000 });
    expect(previous.endDate).toBe('2026-12-31');
    expect(next.startDate).toBe('2027-01-01');
    expect(next.amount).toBe(550000);

    const occ = [
      ...generateOccurrences(previous, window('2026-12-01', '2027-02-28')),
      ...generateOccurrences(next, window('2026-12-01', '2027-02-28')),
    ].map((o) => `${o.date}:${o.amount}`);
    expect(occ.sort()).toEqual([
      '2026-12-07:300000', // salário de novembro
      '2026-12-15:200000',
      '2027-01-08:300000', // salário de dezembro, ainda no valor antigo
      '2027-01-15:220000',
      '2027-02-05:330000',
      '2027-02-15:220000',
    ]);
  });

  it('rejects a month at or before the start', () => {
    expect(() => splitRecurrenceFrom(salary, '2026-09', {})).toThrow(RangeError);
    expect(() => splitRecurrenceFrom(salary, '2026-9', {})).toThrow(RangeError);
  });
});
