import {
  ArrowLeftRight,
  Briefcase,
  Car,
  Circle,
  CreditCard,
  Ellipsis,
  Gift,
  GraduationCap,
  HandCoins,
  HeartPulse,
  House,
  Landmark,
  Laptop,
  PartyPopper,
  PawPrint,
  Plane,
  Repeat,
  Scale,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Tag,
  TrendingUp,
  Undo2,
  Utensils,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/** Ícones das categorias (nomes lucide gravados no banco pelo seed). */
const ICONS: Record<string, LucideIcon> = {
  'arrow-left-right': ArrowLeftRight,
  briefcase: Briefcase,
  car: Car,
  'credit-card': CreditCard,
  ellipsis: Ellipsis,
  gift: Gift,
  'graduation-cap': GraduationCap,
  'hand-coins': HandCoins,
  'heart-pulse': HeartPulse,
  house: House,
  landmark: Landmark,
  laptop: Laptop,
  'party-popper': PartyPopper,
  'paw-print': PawPrint,
  plane: Plane,
  repeat: Repeat,
  scale: Scale,
  shirt: Shirt,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  sparkles: Sparkles,
  tag: Tag,
  'trending-up': TrendingUp,
  'undo-2': Undo2,
  utensils: Utensils,
  zap: Zap,
};

export function categoryIcon(name: string | null | undefined): LucideIcon {
  return (name && ICONS[name]) || Circle;
}
